Enable video backend engine
MiyooCFW/uboot pull request #28
Opened 2023-12-27 13:09 UTC by tiopex

Enable video backend engine to display splash screen or console logs from uboot (in right way :) @nfriedly )

Default, the only splash screen is displayed, to enable console logs with small miyoo logo in left corner we need to add the below entries to `console.cfg`

`silent=` - to enable logs
`splashimage=` - to display small miyoo logo instead fullscreen splash image

example config.cfg:
```
CONSOLE_VARIANT=pocketgo
silent=
splashimage=
```

@TriForceX  FYI to add information to wiki on how to enable console logs in uboot

2023-12-27 21:31 UTC, Apaczer requested changes
Woow I can see uboot console now! :pray: BTW how do I dump that info to some log.txt if possible? Can we drop miyoo-boot.bmp in favor of only miyoo-splash.bmp?
I had some issue at first making silent&splash work simultaneously (sole silent much more readable for my taste), propbably CRLF formatting.

2023-12-27 21:31 UTC, Apaczer commented on configs/miyoo_defconfig
> +CONFIG_VIDEO_LCD_MODE="x:320,y:240,depth:18,pclk_khz:9000,le:39,ri:8,up:2,lo:4,hs:4,vs:10,sync:3,vmode:0"
for 24bpp shouldn't be `depth=24` ? I tried to run fbgradient.c code from kernel lvl but it needs 32bpp framebuffer.

2023-12-27 21:31 UTC, Apaczer commented on include/env_default.h
> +	"splashfile=" "miyoo-splash.bmp" 	"\0"
maybe make it more generic with e.g. #ifdef CONFIG_MIYOO, the same goes for bootm.c with console_variant which is specific only to MiyooCFW. I would suggest to use VENDOR/BOARD variable normally I guess.

2023-12-27 22:28 UTC, tiopex commented
> how do I dump that info to some log.txt if possible?

I'm afraid that there is no such feature in uboot

> Can we drop miyoo-boot.bmp in favor of only miyoo-splash.bmp?

yes, after merging this PR

2023-12-27 22:32 UTC, tiopex commented on configs/miyoo_defconfig
> +CONFIG_VIDEO_LCD_MODE="x:320,y:240,depth:18,pclk_khz:9000,le:39,ri:8,up:2,lo:4,hs:4,vs:10,sync:3,vmode:0"
this depth is only in uboot part, the kernel is using 16bpp

2023-12-28 06:59 UTC, tiopex commented on configs/miyoo_defconfig
> +CONFIG_VIDEO_LCD_MODE="x:320,y:240,depth:18,pclk_khz:9000,le:39,ri:8,up:2,lo:4,hs:4,vs:10,sync:3,vmode:0"
in lcdc.c the only used values for depth are 16 and 18. 24 is not used anywhere.
depth=18 is used to set panel to mode RGB666, depth=16 to set panel to mode RGB565

2023-12-28 09:04 UTC, Apaczer commented on configs/miyoo_defconfig
> +CONFIG_VIDEO_LCD_MODE="x:320,y:240,depth:18,pclk_khz:9000,le:39,ri:8,up:2,lo:4,hs:4,vs:10,sync:3,vmode:0"
ah interesting, was confused while reading sunxi wiki, also I don't recall setting for RGB666 in kernel

2023-12-28 09:08 UTC, Apaczer approved these changes

2023-12-28 14:14 UTC, merged